// <auto-generated />
using System;
using LoadoutConfigurator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoadoutConfigurator.Api.Migrations
{
    [DbContext(typeof(LoadoutContext))]
    [Migration("20260728084847_MakeManufacturerOptional")]
    partial class MakeManufacturerOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ComponentTemplateAcceptedAttachmentType", b =>
                {
                    b.Property<int>("AcceptedAttachmentTypesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AcceptedAttachmentTypesId", "ComponentTemplateId");

                    b.HasIndex("ComponentTemplateId");

                    b.ToTable("ComponentTemplateAcceptedAttachmentType");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.AttachmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AttachmentTypes");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceEur")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeightGrams")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ComponentTemplateId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.ComponentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RealWidthMm")
                        .HasColumnType("TEXT");

                    b.Property<string>("SvgAssetPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentTemplates");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.Loadout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShareToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Loadouts");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.LoadoutItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoadoutId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentSlotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("LoadoutId");

                    b.ToTable("LoadoutItems");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.MountPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttachmentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GridColumn")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GridRow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PositionXPercent")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionYPercent")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentTypeId");

                    b.HasIndex("ComponentTemplateId");

                    b.ToTable("MountPoints");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttachmentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GridColumn")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GridRow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PositionXPercent")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionYPercent")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentTypeId");

                    b.HasIndex("ComponentTemplateId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("ComponentTemplateAcceptedAttachmentType", b =>
                {
                    b.HasOne("LoadoutConfigurator.Api.Models.AttachmentType", null)
                        .WithMany()
                        .HasForeignKey("AcceptedAttachmentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoadoutConfigurator.Api.Models.ComponentTemplate", null)
                        .WithMany()
                        .HasForeignKey("ComponentTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.Component", b =>
                {
                    b.HasOne("LoadoutConfigurator.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoadoutConfigurator.Api.Models.ComponentTemplate", "ComponentTemplate")
                        .WithMany()
                        .HasForeignKey("ComponentTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ComponentTemplate");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.LoadoutItem", b =>
                {
                    b.HasOne("LoadoutConfigurator.Api.Models.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoadoutConfigurator.Api.Models.Loadout", "Loadout")
                        .WithMany("Items")
                        .HasForeignKey("LoadoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Loadout");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.MountPoint", b =>
                {
                    b.HasOne("LoadoutConfigurator.Api.Models.AttachmentType", "AttachmentType")
                        .WithMany()
                        .HasForeignKey("AttachmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoadoutConfigurator.Api.Models.ComponentTemplate", "ComponentTemplate")
                        .WithMany("MountPoints")
                        .HasForeignKey("ComponentTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttachmentType");

                    b.Navigation("ComponentTemplate");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.Slot", b =>
                {
                    b.HasOne("LoadoutConfigurator.Api.Models.AttachmentType", "AttachmentType")
                        .WithMany()
                        .HasForeignKey("AttachmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoadoutConfigurator.Api.Models.ComponentTemplate", "ComponentTemplate")
                        .WithMany("Slots")
                        .HasForeignKey("ComponentTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttachmentType");

                    b.Navigation("ComponentTemplate");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.ComponentTemplate", b =>
                {
                    b.Navigation("MountPoints");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("LoadoutConfigurator.Api.Models.Loadout", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
